// apps/web/src/routes/(app)/stacks/[name]/StackComposeView.svelte
<script lang="ts">
  import { Icon } from "@laber/ui";

  type Props = {
    content: string;
    fileName: string;
  };

  let { content, fileName }: Props = $props();
  let copied = $state(false);

  async function copyToClipboard() {
    await navigator.clipboard.writeText(content);
    copied = true;
    setTimeout(() => (copied = false), 2000);
  }
</script>

<div class="bg-surface-2 border-border overflow-hidden rounded-lg border">
  <div class="border-border flex items-center justify-between border-b px-4 py-2">
    <span class="text-text-secondary font-mono text-xs">{fileName}</span>
    <button
      type="button"
      onclick={copyToClipboard}
      class="text-text-muted hover:text-text-secondary flex items-center gap-1 text-xs transition-colors"
    >
      <Icon>
        {#if copied}
          <path d="M4 8l3 3 5-6" />
        {:else}
          <path d="M5 2H3a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V5M5 2h4l3 3v8a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z" />
        {/if}
      </Icon>
      {copied ? "Copied" : "Copy"}
    </button>
  </div>
  <pre class="overflow-auto p-4 font-mono text-xs leading-relaxed text-text-primary">{content}</pre>
</div>

// apps/web/src/components/StackComposeView.tsx
import { useEffect, useState } from "react";
import { Button } from "@laber/ui";
import { useApiMutation } from "@/lib/queries/actions";
import { stackComposeSave } from "@/lib/queries/stacks";
import MutationNotice from "@/components/MutationNotice";
import { Icon } from "@laber/ui";

export function StackComposeView({
  content,
  fileName,
  stackName,
}: {
  content: string;
  fileName: string;
  stackName: string;
}) {
  const [copied, setCopied] = useState(false);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(content);

  // Parent remounts per stack; this only guards a refetch while viewing.
  useEffect(() => {
    if (!editing) setDraft(content);
  }, [content, editing]);

  const saveMutation = useApiMutation({
    ...stackComposeSave(stackName),
    onSuccess: () => setEditing(false),
  });

  function toggleEditing() {
    setDraft(content);
    // Cancel-path clear: no new mutation fires, so this is the one surviving `reset()`.
    saveMutation.reset();
    setEditing((v) => !v);
  }

  async function copyToClipboard() {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="bg-surface-2 border-border overflow-hidden rounded-lg border">
      <div className="border-border flex items-center justify-between border-b px-4 py-2">
        <span className="text-text-secondary font-mono text-xs">
          {fileName}
        </span>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={toggleEditing}
            className="text-text-muted hover:text-text-secondary flex items-center gap-1 text-xs transition-colors"
          >
            {editing ? "Cancel" : "Edit"}
          </button>
          <button
            type="button"
            onClick={copyToClipboard}
            className="text-text-muted hover:text-text-secondary flex items-center gap-1 text-xs transition-colors"
          >
            <Icon>
              {copied ? (
                <path d="M4 8l3 3 5-6" />
              ) : (
                <path d="M5 2H3a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V5M5 2h4l3 3v8a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z" />
              )}
            </Icon>
            {copied ? "Copied" : "Copy"}
          </button>
        </div>
      </div>
      {editing ? (
        <div className="p-4">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            rows={24}
            className="w-full font-mono text-xs"
          />
          <MutationNotice mutation={saveMutation} errorFallback="Save failed" />
          <div className="mt-2 flex justify-end">
            <Button
              variant="primary"
              size="sm"
              disabled={saveMutation.isPending}
              onClick={() => saveMutation.mutate(draft)}
            >
              {saveMutation.isPending ? "Saving..." : "Save Compose"}
            </Button>
          </div>
        </div>
      ) : (
        <pre className="text-text-primary overflow-auto p-4 font-mono text-xs leading-relaxed">
          {content}
        </pre>
      )}
    </div>
  );
}

export default StackComposeView;
